version: '3'
services:
  mongo:
    image: mongo:5.0.6
    restart: unless-stopped

  nginx:
    image: danieldent/nginx-ssl-proxy
    environment:
      UPSTREAM: app:3000
      SERVERNAME: news.razmadze.me
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  app:
    build: .
    environment:
      # Usually these would go in environmental variables,
      # but for this demo I've left them here
      MONGODB_URL: mongodb://mongo:27017/news-app
      NEWS_URL: https://newsapi.org/v2
      NEWS_TOKEN: 8325c53c613442a183ebfd892adf0308
    ports:
      # Exposing for development, for production nginx container should be used
      - "3000:3000"
    depends_on:
      - mongo
      - nginx
    restart: unless-stopped
